// Generated by CoffeeScript 1.3.3
(function() {
  var Account, AutoClose, Base, Campaign, CardType, Coupon, Customer, Device, Discount, Geocode, InvoiceImport, Notification, NotificationCategory, NotificationOptionAction, Order, Payment, Pci, SAQ,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = (function() {

    function Base(pps_client) {
      this.pps_client = pps_client;
    }

    Base.prototype.getAll = function(params, callback) {
      return this.pps_client.getResource(this.resource_name, params, callback);
    };

    Base.prototype.getById = function(id, callback) {
      return this.pps_client.getResource(this.resource_name + '/' + id, null, callback);
    };

    Base.prototype.post = function(obj, callback) {
      return this.pps_client.postResource(this.resource_name, obj, callback);
    };

    return Base;

  })();

  Pci = (function(_super) {

    __extends(Pci, _super);

    function Pci() {
      return Pci.__super__.constructor.apply(this, arguments);
    }

    Pci.prototype.resource_name = 'Pci';

    return Pci;

  })(Base);

  CardType = (function(_super) {

    __extends(CardType, _super);

    function CardType() {
      return CardType.__super__.constructor.apply(this, arguments);
    }

    CardType.prototype.resource_name = 'CardType';

    return CardType;

  })(Base);

  Account = (function(_super) {

    __extends(Account, _super);

    function Account() {
      return Account.__super__.constructor.apply(this, arguments);
    }

    Account.prototype.resource_name = 'Account';

    return Account;

  })(Base);

  AutoClose = (function(_super) {

    __extends(AutoClose, _super);

    function AutoClose() {
      return AutoClose.__super__.constructor.apply(this, arguments);
    }

    AutoClose.prototype.resource_name = 'AutoClose';

    return AutoClose;

  })(Base);

  Campaign = (function(_super) {

    __extends(Campaign, _super);

    function Campaign() {
      return Campaign.__super__.constructor.apply(this, arguments);
    }

    Campaign.prototype.resource_name = 'Campaign';

    return Campaign;

  })(Base);

  CardType = (function(_super) {

    __extends(CardType, _super);

    function CardType() {
      return CardType.__super__.constructor.apply(this, arguments);
    }

    CardType.prototype.resource_name = 'CardType';

    return CardType;

  })(Base);

  Coupon = (function(_super) {

    __extends(Coupon, _super);

    function Coupon() {
      return Coupon.__super__.constructor.apply(this, arguments);
    }

    Coupon.prototype.resource_name = 'Coupon';

    return Coupon;

  })(Base);

  Customer = (function(_super) {

    __extends(Customer, _super);

    function Customer() {
      return Customer.__super__.constructor.apply(this, arguments);
    }

    Customer.prototype.resource_name = 'Customer';

    return Customer;

  })(Base);

  Device = (function(_super) {

    __extends(Device, _super);

    function Device() {
      return Device.__super__.constructor.apply(this, arguments);
    }

    Device.prototype.resource_name = 'Device';

    return Device;

  })(Base);

  Discount = (function(_super) {

    __extends(Discount, _super);

    function Discount() {
      return Discount.__super__.constructor.apply(this, arguments);
    }

    Discount.prototype.resource_name = 'Discount';

    return Discount;

  })(Base);

  Geocode = (function(_super) {

    __extends(Geocode, _super);

    function Geocode() {
      return Geocode.__super__.constructor.apply(this, arguments);
    }

    Geocode.prototype.resource_name = 'Geocode';

    return Geocode;

  })(Base);

  InvoiceImport = (function(_super) {

    __extends(InvoiceImport, _super);

    function InvoiceImport() {
      return InvoiceImport.__super__.constructor.apply(this, arguments);
    }

    InvoiceImport.prototype.resource_name = 'InvoiceImport';

    return InvoiceImport;

  })(Base);

  Notification = (function(_super) {

    __extends(Notification, _super);

    function Notification() {
      return Notification.__super__.constructor.apply(this, arguments);
    }

    Notification.prototype.resource_name = 'Notification';

    return Notification;

  })(Base);

  NotificationCategory = (function(_super) {

    __extends(NotificationCategory, _super);

    function NotificationCategory() {
      return NotificationCategory.__super__.constructor.apply(this, arguments);
    }

    NotificationCategory.prototype.resource_name = 'NotificationCategory';

    return NotificationCategory;

  })(Base);

  NotificationOptionAction = (function(_super) {

    __extends(NotificationOptionAction, _super);

    function NotificationOptionAction() {
      return NotificationOptionAction.__super__.constructor.apply(this, arguments);
    }

    NotificationOptionAction.prototype.resource_name = 'NotificationOptionAction';

    return NotificationOptionAction;

  })(Base);

  Order = (function(_super) {

    __extends(Order, _super);

    function Order() {
      return Order.__super__.constructor.apply(this, arguments);
    }

    Order.prototype.resource_name = 'Order';

    return Order;

  })(Base);

  SAQ = (function(_super) {

    __extends(SAQ, _super);

    function SAQ() {
      return SAQ.__super__.constructor.apply(this, arguments);
    }

    SAQ.prototype.resource_name = 'SAQ';

    return SAQ;

  })(Base);

  Payment = (function(_super) {

    __extends(Payment, _super);

    function Payment() {
      return Payment.__super__.constructor.apply(this, arguments);
    }

    Payment.prototype.resource_name = 'Payment';

    Payment.prototype.post = function(payment, callback) {
      var merchId;
      merchId = payment.merchantId;
      return this.pps_client.postResource(this.resource_name + "?merchantId=" + merchId, JSON.stringify(payment), callback);
    };

    Payment.prototype.put = function(payment, callback) {
      var paymentId;
      paymentId = payment.id;
      return this.pps_client.putResource(this.resource_name + "/" + paymentId, JSON.stringify(payment), callback);
    };

    return Payment;

  })(Base);

  module.exports = {
    Pci: Pci,
    Account: Account,
    AutoClose: AutoClose,
    Campaign: Campaign,
    CardType: CardType,
    Coupon: Coupon,
    Customer: Customer,
    Device: Device,
    Discount: Discount,
    Geocode: Geocode,
    InvoiceImport: InvoiceImport,
    Notification: Notification,
    NotificationCategory: NotificationCategory,
    NotificationOptionAction: NotificationOptionAction,
    Order: Order,
    SAQ: SAQ,
    Payment: Payment
  };

}).call(this);
